import React from "react";

const GlobalContext = React.createContext({
  companyName: "",
  setCompanyName: () => {},
  companyAddress: "",
  setCompanyAddress: () => {},
  companyCityStateZip: "",
  setCompanyCityStateZip: () => {},
  companyCountry: "",
  setCompanyCountry: () => {},
  yourName: "",
  setYourName: () => {},
  clientCompanyName: "",
  setClientCompanyName: () => {},
  clientCompanyAddress: "",
  setClientCompanyAddress: () => {},
  clientCompanyCityStateZip: "",
  setClientCompanyCityStateZip: () => {},
  clientCompanyCountry: "",
  setClientCompanyCountry: () => {},
  invoiceName: "",
  setInvoiceName: () => {},
  invoiceDate: "",
  setInvoiceDate: () => {},
  dueDate: "",
  setDueDate: () => {},
  invoiceNameTag: "",
  setInvoiceNameTag: () => {},
  invoiceDateTag: "",
  setInvoiceDateTag: () => {},
  dueDateTag: "",
  setDueDateTag: () => {},
});

export default GlobalContext;
